config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Simple App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer center">
  <small>
    <a href="http://antonye.ru/">ANTON YE</a>
    Powered by Ruby on Rails
  </small>

</footer>

app/views/layouts/_header.html.erb
<header>
  <%= nav_bar fixed: :top, brand: "SIMPLE APP", responsive: true do %>
      <%= menu_group do %>
          <%= menu_item "Home", root_path %>
          <%= menu_item "Help", help_path %>

          <%= menu_divider %>
      <% end %>
  <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center">
<h1>StaticPages#<%= yield(:title) %></h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>